repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: check-yaml
      -   id: check-case-conflict
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
      -   id: black
  -   repo: https://github.com/PyCQA/pylint
      rev: v3.0.0a7
      hooks:
      -   id: pylint
  -   repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
      -   id: flake8
